<?php
/**
 * @file
 * sms_turbosms.module file.
 *
 * @see https://www.drupal.org/sandbox/Vik/1993102
 */

/**
 * Implements hook_gateway_info().
 *
 * Create new sms gateway.
 *
 * Writing a Gateway Module.
 *
 * Check http://drupal.org/node/362261
 *
 * @return array
 */
function sms_turbosms_gateway_info() {
  return array(
    'sms_turbosms' => array(
      'name'           => t('TurboSMS UA Gateway'),
      'send'           => 'sms_turbosms_send',
      'receive'        => TRUE,
      'configure form' => 'sms_turbosms_gateway_admin_form',
    ),
  );
}

/**
 * TurboSMS config form callback.
 *
 * @return array
 *   Drupal form array.
 */
function sms_turbosms_gateway_admin_form() {
  $form = array();
  $form['sms_turbosms'] = array(
    '#type'   => 'fieldset',
    '#title'  => t('TurboSMS gateway settings'),
  );
  $form['sms_turbosms']['sign'] = array(
    '#type'     => 'textfield',
    '#title'    => t('TurboSMS Sign'),
    '#required' => TRUE,
  );
  return $form;
}

/**
 * Gateway send function.
 *
 * @param string $number
 *   Telephone number.
 *
 * @param string $message
 *   Message.
 *
 * @param array $options
 *   Options array.
 *
 * @return array
 *   Result array.
 */
function sms_turbosms_send($number, $message, $options) {
  $gateway = new TurboSMS();

  if (!$gateway) {
    return $gateway->getStatus();
  }
  $result = $gateway->send($number, $message)->getStatus();

  return $result;
}
