<?php
/**
 * @file
 * sms_turbosms.module file.
 *
 * @see https://www.drupal.org/sandbox/Vik/1993102
 */

/**
 * Implements hook_gateway_info().
 *
 * Create new sms gateway.
 *
 * Writing a Gateway Module.
 *
 * Check http://drupal.org/node/362261
 *
 * @return array
 */
function sms_turbosms_gateway_info() {
  return array(
    'sms_turbosms' => array(
      'name'           => t('TurboSMS UA Gateway'),
      'send'           => 'sms_turbosms_send',
      'receive'        => TRUE,
      'configure form' => 'sms_turbosms_gateway_admin_form',
    ),
  );
}

/**
 * TurboSMS config form callback.
 *
 * @return array
 *   Drupal form array.
 */
function sms_turbosms_gateway_admin_form() {
  $form = array();
  $form['sms_turbosms'] = array(
    '#type'   => 'fieldset',
    '#title'  => t('TurboSMS gateway settings'),
  );
  $form['sms_turbosms']['sign'] = array(
    '#type'     => 'textfield',
    '#title'    => t('TurboSMS Sign'),
    '#required' => TRUE,
  );
  return $form;
}

/**
 * Gateway send function.
 *
 * @param string $number
 *   Telephone number.
 *
 * @param string $message
 *   Message.
 *
 * @param array $options
 *   Options array.
 *
 * @return array
 *   Result array.
 */
function sms_turbosms_send($number, $message, $options) {
  return _write_message($number, $message);
}

/**
 * Helper function for a writing entry to remote turbosms db user table.
 *
 * @param string $number
 *   Telephone number.
 *
 * @param string $message
 *   Message.
 *
 * @return array
 *   Result array.
 */
function _write_message($number = NULL, $message = NULL) {
  if (empty($number)) {
    return array(
      'status'    => FALSE,
      'message'   => 'Bad phone number: %number',
      'variables' => array('%number', $number),
    );
  }
  if (sms_turbosms_check_gateway_db()) {
    $table_name = variable_get("sms_turbosms_login", "");
    $transaction_id = db_insert($table_name)
      ->fields(array(
        'number'  => $number,
        'sign'    => variable_get("sms_turbosms_sender", ""),
        'message' => $message,
      ))
      ->execute();
    // Check db_insert status.
    if (!empty($transaction_id)) {
      $result = array(
        'status' => TRUE,
      );
    }
    else {
      $result = array(
        'status'    => FALSE,
        'message'   => 'Something happened wrong while inserting new entry to "%table" table',
        'variables' => array('%table', $table_name),
      );
    }
    db_set_active();
    return $result;
  }
  return FALSE;
}

/**
 * Get database connection info.
 *
 * @return array
 *   Array of database connection info.
 */
function sms_turbosms_check_gateway_db() {
  try {
    // This doesn't actually test the connection.
    db_set_active('sms_turbosms');
    // Now actually do a check.
    Database::getConnection();
  }
  catch (Exception $e) {
    $result = array(
      'status'    => FALSE,
      'message'   => 'Failed to connect to your database server. The server reports the following message: %error.<ul><li>Is the database server running?</li><li>Does the database exist, and have you entered the correct database name?</li><li>Have you entered the correct username and password?</li><li>Have you entered the correct database hostname?</li></ul>',
      'variables' => array('%error', $e->getMessage()),
    );
    return $result;
  }
  return TRUE;
}
